AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Description: A great application description goes here

Parameters:
  Environment:
    Type: String
    Default: sandbox
    AllowedValues:
      - production
      - staging
      - sandbox
      - development
      - release

## Create Resources here
# Resources:
